apiVersion: v2
name: secrets-manager
description: Handles secrets on the platform
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: openbao
    version: 0.19.2
    repository: "@openbao"
