# global:
#   tlsDisable: true

ui:
  enabled: true

# server:
  # extraArgs: "-dev"
  # dev:
  #   enabled: true
  # dataStorage:
  #   enabled: false
  # auditStorage:
  #   enabled: true

# injector:
#   enabled: true
